name: My CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Java and Maven
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run tests
        run: mvn test
  prepare-environment:
    needs: test
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Stop docker compose
        run: docker-compose down
      - name: Stop and remove containers, networks
        run: docker rm -vf $(docker ps -aq)
      - name: Remove unused data
        run: docker system prune -a -f
  deploy:
    runs-on: self-hosted
    needs: prepare-environment
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Docker compose
        run: docker-compose up -d
